# .github/workflows/deploy.yml
name: Deploy to ECS Fargate

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::545009830461:role/github-actions-deploy-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          docker build -t 545009830461.dkr.ecr.ap-northeast-2.amazonaws.com/eroom-backend:$IMAGE_TAG .
          docker push 545009830461.dkr.ecr.ap-northeast-2.amazonaws.com/eroom-backend:$IMAGE_TAG

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .github/ecs/task-definition.json
          service: eroom-backend-service
          cluster: eroom-cluster
          wait-for-service-stability: true
